name: Deploy Blank Page via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Blank Site
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Sync files via FTP (First Website)
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; mirror -R -e ./public/ ./"

    - name: Sync files via FTP (Second Website)
      run: |
        lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.FTP_USERNAME_2 }},${{ secrets.FTP_PASSWORD_2 }} ${{ secrets.FTP_SERVER_2 }}; mirror -R -e ./public/ ./"
